### ISSUE TITLE
[ncm2_jedi@yarp] Job is dead

### ISSUE THREAD

**Issue by hiphamster** [ncm2/ncm2-jedi#15]
I'm on mac. I've been able to trace the error, not sure what to do next:

ncm2_jedi.vim:
` 18 if g:ncm2_jedi#python_version != 2
 19     let g:ncm2_jedi#proc = yarp#py3('ncm2_jedi')
 20 else`

nvim-yarp/pythonx/yarp.py
`nvim.call('yarp#core#channel_started', yarpid, nvim.channel_id)`

the actual call:
args: ['~/.vim/bundle/nvim-yarp/pythonx/yarp.py', '/var/folders/jg/ftzn1w1d0p10bn6znb8y5pfc0000gp/T/nvimusOWoh/0', '3', 'ncm2_jedi']

in the above, the socket file is wrong, every time. If manually run the command with the right file, it seems to run with out errors

any help is appreciated

**Comment by roxma** [comment]
> in the above, the socket file is wrong, every time.

The socket file should be the same as `v:servername`, could you show bot the wrong socket path and the  correct `v:servername`?

**Comment by hiphamster** [comment]
I did a bit more digging, and tried to capture `v:servername`. As you mentioned it, it's the same as socket path.  Then i found this:
`/var/folders/jg/ftzn1w1d0p10bn6znb8y5pfc0000gp/T/nvimSRbWEX/0
/var/folders/jg/ftzn1w1d0p10bn6znb8y5pfc0000gp/T/nvimSRbWEX/0
[ncm2_jedi@yarp] Traceback (most recent call last):
[ncm2_jedi@yarp]   File "/Users/ayelluas/.vim/bundle/nvim-yarp/pythonx/yarp.py", line 70, in <module>
[ncm2_jedi@yarp]     module_obj = importlib.import_module(module)
[ncm2_jedi@yarp]   File "/Users/ayelluas/.pyenv/versions/3.7.1/lib/python3.7/importlib/__init__.py", line 127, in import_module
[ncm2_jedi@yarp]     return _bootstrap._gcd_import(name[level:], package, level)
[ncm2_jedi@yarp]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[ncm2_jedi@yarp]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[ncm2_jedi@yarp]   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[ncm2_jedi@yarp]   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
[ncm2_jedi@yarp]   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
[ncm2_jedi@yarp]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[ncm2_jedi@yarp]   File "/Users/ayelluas/.vim/bundle/ncm2-jedi/pythonx/ncm2_jedi.py", line 7, in <module>
[ncm2_jedi@yarp]     import jedi
[ncm2_jedi@yarp] ModuleNotFoundError: No module named 'jedi'
[ncm2_jedi@yarp] Job is dead. cmd=['/Users/ayelluas/.pyenv/versions/neovim3/bin/python', '-u', '/Users/ayelluas/.vim/bundle/nvim-yarp/pythonx/yarp.py', '/var/f
olders/jg/ftzn1w1d0p10bn6znb8y5pfc0000gp/T/nvimSRbWEX/0', 3, 'ncm2_jedi']`

Turns out `jedi` module was not installed . I use pyenv-virtualenv, so once i installed `jedi` in `neovim3` virtualenv, the problem went away.

**Comment by z-huabao** [comment]
In my case, I install 'jedi' in `/usr/local/lib/python3.5` but 'neovim3' in `~/.local/lib/python3.5` and get error

**Comment by nikartix** [comment]
In my case, I had to install jedi and pynvim in a virtual environment. Can I avoid installing these in all my environments?
