### ISSUE TITLE
Neovim gutter icon inconsistant.

### ISSUE THREAD

**Issue by kierun** [ncm2/ncm2-jedi#17]
I am getting this weird behaviour. If i write some garbage, I get the correct gutter icon like so:

![screenshot](https://user-images.githubusercontent.com/3079575/54022144-bd136280-4189-11e9-9678-56eec5d51553.png)

When I correct the mistake, the gutter icon persists. Any idea?

![screenshot2](https://user-images.githubusercontent.com/3079575/54022152-c270ad00-4189-11e9-80c8-90561c149ee1.png)

**Comment by roxma** [comment]
I think you have posted the issue on the wrong repo.

ncm2-jedi only offers completion. It does not update the gutter.

**Comment by kierun** [comment]
My apologies. I thought it did. Hum…
