### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by moshiur-raj** [ncm2/ncm2-jedi#28]
Hello, I am using neovim v0.4.4 on arch linux. I have python, python-pynvim, python-jedi packages installed. But ncm2_jedi does not work. The error message shown at the bottom is : `[ncm2_jedi@yarp] AttributeError: 'PosixPath' object has no attribute 'endswith'` .

**Comment by jorgejarai** [comment]
I'm having the same problem too (same version and using Arch as well)

**Comment by moshiur-raj** [comment]
Installing jedi using pip solves this problem.

**Comment by jorgejarai** [comment]
It worked! I had ```python-jedi``` installed from ```pacman```, that's probably it didn't work. Once I removed it and installed ```jedi``` from ```pip``` it started to work as intended.

**Comment by moshiur-raj** [comment]
okay, apparently pacman has jedi 0.17.0 but pip had jedi 0.17.2 
So, I installed jedi from aur and it works fine now. I don't really use pip since I do not use that many python packages and I also don't use virtual environments. So I'll use the AUR version for now and switch to the official repo when it's updated.
