### ISSUE TITLE
when edit .py file in neovim,it shows TypeError.

### ISSUE THREAD

**Issue by Esonhugh** [ncm2/ncm2-jedi#29]
[ncm2_jedi@yarp] TypeError: __init__() takes from 1 to 2 positional arguments but 5 positional arguments (and 1 keywo
rd-only argument) were given
^show with red in command area
also it give me no keyword in floating window.
How can i fix it?

**Comment by Esonhugh** [comment]
forgive my dumb issue.

**Comment by bo5o** [comment]
did you figure out the reason?

**Comment by bo5o** [comment]
I have made a PR that should fix this error and work with latest jedi (0.18.0)

**Comment by git314** [comment]
I am having the same issue and I am on jedi 0.18.0.

**Comment by git314** [comment]
@Esonhugh How did you fix this problem?

**Comment by xuzuoyang** [comment]
> @Esonhugh How did you fix this problem?

Install jedi<0.18.0 or wait for the fix pr to be merged.

**Comment by Esonhugh** [comment]
temp  change to another plugin (doge)
No update the jedi or wait PR.
Now we has PR
