### ISSUE TITLE
Add g:ncm2_jedi#settings

### ISSUE THREAD

**Issue by theFool32** [ncm2/ncm2-jedi#4]
Some packages like numpy, torch, tensorflow are so large and it takes a long time to complete them.
Anyway to cache it ahead?
Thanks.

**Comment by antonzub1** [comment]
@roxma, first of all - thank you very much for doing great job and delivering such a good product. It works really well, except speed of completion on large packages, as @theFool32 mentioned. I am wondering - is it possible to utilize [Jedi cache](https://jedi.readthedocs.io/en/latest/docs/settings.html) somehow to make completions more fast?

**Comment by roxma** [comment]
Thanks for the info @zabulazza 

I will get some free time and test it.

**Comment by roxma** [comment]
@zabulazza 

[filesystem-cache](https://jedi.readthedocs.io/en/latest/docs/settings.html#filesystem-cache) is enabled by default.

I'm not sure what I can do for this.

You could try this fork for now: https://github.com/ncm2/ncm2-jedi/issues/6 

I'm going to add `g:ncm2_jedi#settings` for customized settings for https://jedi.readthedocs.io/en/latest/docs/settings.html and then close this issue.
